# -*- coding: utf-8 -*-
"""Shadow_&_Reflection_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d66B4H4VX0vHXWGkKqE2gRlls-znjeiT

## Section 1 - Setup & Config
"""

import os, glob, random, math
import cv2
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as T

print("Torch version:", torch.__version__)
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

# Global config
CFG = {
    "device": device,
    "gan_img_size": 256,       # common size for GAN inputs
    "batch_size": 4,
    "epochs_shadow": 20,       # can be adjusted acordingly
    "epochs_reflection": 10,   # same as above
    "lr_g": 2e-4,
    "lr_d": 2e-4,
}

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

set_seed(42)

"""## Section 2 - Utility Functions"""

def show_images(imgs, titles=None, cols=3, figsize=(12, 4)):
    n = len(imgs)
    rows = math.ceil(n / cols)
    plt.figure(figsize=figsize)
    for i, im in enumerate(imgs):
        plt.subplot(rows, cols, i+1)
        im_disp = im.copy()
        if im_disp.dtype != np.uint8:
            im_disp = np.clip(im_disp, 0, 1)
        plt.imshow(im_disp)
        if titles is not None and i < len(titles):
            plt.title(titles[i])
        plt.axis("off")
    plt.tight_layout()
    plt.show()

def tensor_to_image(t):
    t = t.detach().cpu().clamp(-1, 1)
    t = (t + 1) / 2
    return t.permute(1, 2, 0).numpy()

"""## Section 3 - Database Setup"""

import kagglehub

# ISTD: Image Shadow Triplets dataset
istd_path = kagglehub.dataset_download("sabarinathan/istd-dataset")
print("ISTD dataset at:", istd_path)

# SIRR: Single-Image Reflection Removal dataset
sirr_path = kagglehub.dataset_download("siboooo/singleimagereflectionremovaldataset")
print("SIRR dataset at:", sirr_path)

# Adjusting for unifromly extracted folder names:
istd_root = os.path.join(istd_path, "ISTD_Dataset")
sirr_root = os.path.join(sirr_path, "Single-Image-Reflection-Removal-Dataset")

print("ISTD root:", istd_root)
print("SIRR root:", sirr_root)

"""## Section 4 – Shadows (ISTD): Classical IP + Dataset

4.1 Load ISTD triplets
"""

def _get_pngs(folder):
    return sorted(glob.glob(os.path.join(folder, "*.png")))

def load_istd_triplets(root):
    trainA = _get_pngs(os.path.join(root, "train", "train_A"))  # shadow image
    trainB = _get_pngs(os.path.join(root, "train", "train_B"))  # shadow mask GT
    trainC = _get_pngs(os.path.join(root, "train", "train_C"))  # shadow-free GT

    testA  = _get_pngs(os.path.join(root, "test", "test_A"))
    testB  = _get_pngs(os.path.join(root, "test", "test_B"))
    testC  = _get_pngs(os.path.join(root, "test", "test_C"))

    train_triplets = list(zip(trainA, trainB, trainC))
    test_triplets  = list(zip(testA, testB, testC))
    print(f"ISTD: {len(train_triplets)} train triplets, {len(test_triplets)} test triplets")
    return train_triplets, test_triplets

istd_train, istd_test = load_istd_triplets(istd_root)

# Sanity check
a_path, b_path, c_path = istd_train[0]
A_bgr = cv2.imread(a_path)
B_mask = cv2.imread(b_path, cv2.IMREAD_GRAYSCALE)
C_bgr = cv2.imread(c_path)

A_rgb = cv2.cvtColor(A_bgr, cv2.COLOR_BGR2RGB)
C_rgb = cv2.cvtColor(C_bgr, cv2.COLOR_BGR2RGB)
show_images([A_rgb, B_mask, C_rgb], ["Shadow (A)", "Mask GT (B)", "Clean GT (C)"], cols=3)

"""4.2 Classical shadow mask + edges"""

def classical_shadow_mask(img_bgr):
    gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)
    # Otsu threshold (auto)
    _, thr = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)

    kernel = np.ones((5,5), np.uint8)
    opened = cv2.morphologyEx(thr, cv2.MORPH_OPEN, kernel)
    closed = cv2.morphologyEx(opened, cv2.MORPH_CLOSE, kernel)
    return closed

def classical_shadow_edges(img_bgr):
    gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)
    gx = cv2.Sobel(gray, cv2.CV_32F, 1, 0, ksize=3)
    gy = cv2.Sobel(gray, cv2.CV_32F, 0, 1, ksize=3)
    mag = cv2.magnitude(gx, gy)
    mag = cv2.normalize(mag, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)
    return mag

# quick visual example
example_mask = classical_shadow_mask(A_bgr)
example_edges = classical_shadow_edges(A_bgr)
show_images(
    [A_rgb, example_mask, example_edges],
    ["Shadow Input", "Classical Shadow Mask", "Shadow Edges (Sobel)"],
    cols=3
)

"""4.3 ShadowDataset (5-channel input) + loaders"""

class ShadowDataset(Dataset):
    """
    Input  (X): 5 channels
        - RGB shadow image     (3)
        - classical shadow mask (1)
        - classical Sobel edges (1)
    Target (Y): 3-channel RGB shadow-free image
    """
    def __init__(self, triplets, img_size):
        self.triplets = triplets
        self.size = (img_size, img_size)
        self.tf = T.Compose([
            T.ToPILImage(),
            T.Resize(self.size),
            T.ToTensor(),
        ])

    def __len__(self):
        return len(self.triplets)

    def __getitem__(self, idx):
        a_path, b_path, c_path = self.triplets[idx]
        shadow_bgr = cv2.imread(a_path)
        clean_bgr  = cv2.imread(c_path)

        # classical features
        mask_u8  = classical_shadow_mask(shadow_bgr)
        edges_u8 = classical_shadow_edges(shadow_bgr)

        # RGB images
        shadow_rgb = cv2.cvtColor(shadow_bgr, cv2.COLOR_BGR2RGB)
        clean_rgb  = cv2.cvtColor(clean_bgr,  cv2.COLOR_BGR2RGB)

        shadow_t = self.tf(shadow_rgb)
        clean_t  = self.tf(clean_rgb)

        # masks to tensors
        mask_resized  = cv2.resize(mask_u8,  self.size, interpolation=cv2.INTER_NEAREST)
        edges_resized = cv2.resize(edges_u8, self.size, interpolation=cv2.INTER_NEAREST)

        mask_t  = torch.from_numpy(mask_resized / 255.0).float().unsqueeze(0)  # 1xHxW
        edges_t = torch.from_numpy(edges_resized / 255.0).float().unsqueeze(0) # 1xHxW

        inp_5ch = torch.cat([shadow_t, mask_t, edges_t], dim=0)  # 5xHxW

        # map to [-1,1]
        inp_5ch = inp_5ch * 2 - 1
        clean_t = clean_t * 2 - 1

        return inp_5ch, clean_t

shadow_train_ds = ShadowDataset(istd_train, CFG["gan_img_size"])
shadow_test_ds  = ShadowDataset(istd_test,  CFG["gan_img_size"])

shadow_train_dl = DataLoader(shadow_train_ds, batch_size=CFG["batch_size"],
                             shuffle=True, num_workers=0)
shadow_test_dl  = DataLoader(shadow_test_ds,  batch_size=1,
                             shuffle=False, num_workers=0)

print("Shadow batches:", len(shadow_train_dl), "train,", len(shadow_test_dl), "test")

A_batch, B_batch = next(iter(shadow_train_dl))
print("Input shape (shadow):", A_batch.shape, "Target shape:", B_batch.shape)

"""## Section 5 – Shared Pix2Pix GAN Architecture"""

def gradient_loss(pred, gt):

    # Horizontal gradients
    dp_h = pred[..., :, 1:] - pred[..., :, :-1]
    gp_h = gt[..., :, 1:]   - gt[..., :, :-1]

    # Vertical gradients
    dp_v = pred[..., 1:, :] - pred[..., :-1, :]
    gp_v = gt[..., 1:, :]   - gt[..., :-1, :]

    # Finding the smallest compatible shapes across ALL gradient tensors
    H = min(dp_h.shape[2], gp_h.shape[2], dp_v.shape[2], gp_v.shape[2])
    W = min(dp_h.shape[3], gp_h.shape[3], dp_v.shape[3], gp_v.shape[3])

    # Cropping ALL of them to EXACT same shape
    dp_h = dp_h[:, :, :H, :W]
    gp_h = gp_h[:, :, :H, :W]
    dp_v = dp_v[:, :, :H, :W]
    gp_v = gp_v[:, :, :H, :W]

    # Now safe to compute final loss
    loss_h = F.l1_loss(torch.abs(dp_h), torch.abs(gp_h))
    loss_v = F.l1_loss(torch.abs(dp_v), torch.abs(gp_v))

    return loss_h + loss_v


class UNetBlock(nn.Module):
    def __init__(self, in_ch, out_ch, down=True, use_bn=True, act='relu'):
        super().__init__()
        if down:
            layers = [nn.Conv2d(
                in_ch, out_ch, 4, 2, 1,
                padding_mode="reflect",  # important
                bias=not use_bn
            )]
        else:
            layers = [nn.ConvTranspose2d(
                in_ch, out_ch, 4, 2, 1,
                bias=not use_bn
            )]
        if use_bn:
            layers.append(nn.BatchNorm2d(out_ch))
        if act == 'relu':
            layers.append(nn.ReLU(inplace=False))
        else:
            layers.append(nn.LeakyReLU(0.2, inplace=False))
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)


class Pix2PixGenerator(nn.Module):
    def __init__(self, in_ch=5, out_ch=3, base=64):
        super().__init__()
        # encoder
        self.d1 = UNetBlock(in_ch,    base,   down=True,  use_bn=False, act='lrelu')
        self.d2 = UNetBlock(base,     base*2, down=True,  act='lrelu')
        self.d3 = UNetBlock(base*2,   base*4, down=True,  act='lrelu')
        self.d4 = UNetBlock(base*4,   base*8, down=True,  act='lrelu')
        self.d5 = UNetBlock(base*8,   base*8, down=True,  act='lrelu')
        self.d6 = UNetBlock(base*8,   base*8, down=True,  act='lrelu')
        self.d7 = UNetBlock(base*8,   base*8, down=True,  act='lrelu')
        self.b  = UNetBlock(base*8,   base*8, down=True,  use_bn=False, act='lrelu')

        # decoder
        self.u1 = UNetBlock(base*8,   base*8, down=False)
        self.u2 = UNetBlock(base*16,  base*8, down=False)
        self.u3 = UNetBlock(base*16,  base*8, down=False)
        self.u4 = UNetBlock(base*16,  base*8, down=False)
        self.u5 = UNetBlock(base*16,  base*4, down=False)
        self.u6 = UNetBlock(base*8,   base*2, down=False)
        self.u7 = UNetBlock(base*4,   base,   down=False)

        self.out = nn.Sequential(
            nn.ConvTranspose2d(base*2, out_ch, 4, 2, 1),
            nn.Tanh()
        )

    def forward(self, x):
        H, W = x.shape[-2], x.shape[-1]

        d1 = self.d1(x)
        d2 = self.d2(d1)
        d3 = self.d3(d2)
        d4 = self.d4(d3)
        d5 = self.d5(d4)
        d6 = self.d6(d5)
        d7 = self.d7(d6)
        b  = self.b(d7)

        u1 = self.u1(b)
        u2 = self.u2(torch.cat([u1, d7], dim=1))
        u3 = self.u3(torch.cat([u2, d6], dim=1))
        u4 = self.u4(torch.cat([u3, d5], dim=1))
        u5 = self.u5(torch.cat([u4, d4], dim=1))
        u6 = self.u6(torch.cat([u5, d3], dim=1))
        u7 = self.u7(torch.cat([u6, d2], dim=1))
        out = self.out(torch.cat([u7, d1], dim=1))

        # enforce exact size match
        if out.shape[-2] != H or out.shape[-1] != W:
            out = F.interpolate(out, size=(H, W), mode="bilinear", align_corners=False)

        return out


class PatchDiscriminator(nn.Module):
    def __init__(self, in_ch=5+3, base=64):
        super().__init__()

        def C(i, o, norm=True):
            layers = [nn.Conv2d(i, o, 4, 2, 1, padding_mode="reflect")]
            if norm:
                layers.append(nn.BatchNorm2d(o))
            layers.append(nn.LeakyReLU(0.2, inplace=False))
            return layers

        self.net = nn.Sequential(
            *C(in_ch,   base,   norm=False),
            *C(base,    base*2),
            *C(base*2,  base*4),
            nn.Conv2d(base*4, 1, 4, 1, 1)
        )

    def forward(self, inp, tgt):
        x = torch.cat([inp, tgt], dim=1)
        return self.net(x)

print("Shared GAN architecture ready.")

"""## Section 6 – Train on Shadows (ISTD)"""

G_shadow = Pix2PixGenerator(in_ch=5, out_ch=3).to(device)
D_shadow = PatchDiscriminator(in_ch=5+3).to(device)

optG_s = torch.optim.Adam(G_shadow.parameters(), lr=CFG["lr_g"], betas=(0.5, 0.999))
optD_s = torch.optim.Adam(D_shadow.parameters(), lr=CFG["lr_d"], betas=(0.5, 0.999))

print("Training on Shadows (ISTD)...")
for epoch in range(CFG["epochs_shadow"]):
    G_shadow.train(); D_shadow.train()
    lossD_epoch, lossG_epoch = [], []

    for A, B in shadow_train_dl:
        A = A.to(device)
        B = B.to(device)

        # --- Train Discriminator ---
        fakeB = G_shadow(A)
        real = D_shadow(A, B)
        fake = D_shadow(A, fakeB.detach())

        loss_D = 0.5 * (
            F.mse_loss(real, torch.ones_like(real)) +
            F.mse_loss(fake, torch.zeros_like(fake))
        )
        optD_s.zero_grad()
        loss_D.backward()
        optD_s.step()

        # --- Train Generator ---
        fakeB = G_shadow(A)
        pred_fake = D_shadow(A, fakeB)

        adv  = F.mse_loss(pred_fake, torch.ones_like(pred_fake))
        l1   = F.l1_loss(fakeB, B)
        grad = gradient_loss(fakeB, B)

        loss_G = adv + 50.0 * l1 + 5.0 * grad

        optG_s.zero_grad()
        loss_G.backward()
        optG_s.step()

        lossD_epoch.append(loss_D.item())
        lossG_epoch.append(loss_G.item())

    print(f"[Shadow] Epoch {epoch+1}/{CFG['epochs_shadow']} "
          f"D={np.mean(lossD_epoch):.4f} G={np.mean(lossG_epoch):.4f}")

    # quick visual
    G_shadow.eval()
    with torch.no_grad():
        A_s, B_s = next(iter(shadow_test_dl))
        A_s, B_s = A_s.to(device), B_s.to(device)
        out = G_shadow(A_s)[0]
        imgs = [
            tensor_to_image(A_s[0][:3]),  # only RGB part
            tensor_to_image(out),
            tensor_to_image(B_s[0]),
        ]
        show_images(imgs, ["Input Shadow", "GAN Output", "GT Clean"], cols=3)

torch.save(G_shadow.state_dict(), "G_shadow_5ch.pt")
torch.save(D_shadow.state_dict(), "D_shadow_5ch.pt")
print("Saved shadow models.")

"""## Section 7 – Reflections (SIRR): Classical IP + Dataset

7.1 Load SIRR pairs
"""

import glob

print("Dataset root:", sirr_path)

sirr_root = os.path.join(sirr_path, "trainigPairs")
print("USING SIRR ROOT:", sirr_root)
print("Folders:", os.listdir(sirr_root))


def load_sirr_pairs(root, limit=None, split_ratio=0.8):
    A_dir = os.path.join(root, "A")  # CLEAN
    B_dir = os.path.join(root, "B")  # REFLECTED

    clean_files     = sorted(glob.glob(os.path.join(A_dir, "*.*")))
    reflected_files = sorted(glob.glob(os.path.join(B_dir, "*.*")))

    print(f"Found {len(clean_files)} clean, {len(reflected_files)} reflected")

    if limit:
        clean_files     = clean_files[:limit]
        reflected_files = reflected_files[:limit]

    # Correct pairing → (reflected, clean)
    file_pairs = list(zip(reflected_files, clean_files))

    split = int(len(file_pairs) * split_ratio)
    train_pairs = file_pairs[:split]
    test_pairs  = file_pairs[split:]

    def read_pairs(pairs):
        data = []
        for ref_path, clean_path in pairs:
            ref_img  = cv2.imread(ref_path)
            clean_img = cv2.imread(clean_path)

            if ref_img is None:
                print("Failed to read REF:", ref_path)
                continue
            if clean_img is None:
                print("Failed to read CLEAN:", clean_path)
                continue

            data.append((ref_img, clean_img))

        return data

    train_data = read_pairs(train_pairs)
    test_data  = read_pairs(test_pairs)

    print(f"Loaded {len(train_data)} train and {len(test_data)} test.")
    return train_data, test_data


# Load dataset now
sirr_train, sirr_test = load_sirr_pairs(sirr_root)

# Quick visualization
def show(img, title):
    plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    plt.title(title)
    plt.axis("off")

ref_img, clean_img = sirr_train[0]

plt.figure(figsize=(8,4))
plt.subplot(1,2,1); show(ref_img, "Reflected")
plt.subplot(1,2,2); show(clean_img, "Clean GT")
plt.show()

print("Loaded reflection image shape:", ref_img.shape)

"""7.2 Classical reflection mask + edges"""

def classical_reflection_mask(img_bgr):
    gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)

    gx = cv2.Sobel(gray, cv2.CV_32F, 1, 0, ksize=3)
    gy = cv2.Sobel(gray, cv2.CV_32F, 0, 1, ksize=3)
    mag = cv2.magnitude(gx, gy)
    mag_norm = cv2.normalize(mag, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)

    _, bright = cv2.threshold(gray, 180, 255, cv2.THRESH_BINARY)
    _, low_grad = cv2.threshold(mag_norm, 40, 255, cv2.THRESH_BINARY_INV)

    refl = cv2.bitwise_and(bright, low_grad)
    refl = cv2.morphologyEx(refl, cv2.MORPH_CLOSE, np.ones((7,7), np.uint8))
    return refl


def classical_reflection_edges(img_bgr):
    gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)
    gx = cv2.Sobel(gray, cv2.CV_32F, 1, 0)
    gy = cv2.Sobel(gray, cv2.CV_32F, 0, 1)
    mag = cv2.magnitude(gx, gy)
    return cv2.normalize(mag, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)


# Verify output
refl_bgr, clean_bgr = sirr_train[0]
m = classical_reflection_mask(refl_bgr)
e = classical_reflection_edges(refl_bgr)

show_images([refl_bgr, m, e],
            ["Reflected", "Reflection Mask", "Reflection Edges"], cols=3)

def tensor_to_image(t):
    """
    Convert a [-1,1] normalized tensor (3×H×W) into an RGB uint8 H×W×3 image.
    """
    img = (t.detach().cpu().numpy() + 1) / 2  # [0,1]
    img = np.clip(img, 0, 1)
    img = (img * 255).astype(np.uint8)
    img = img.transpose(1, 2, 0)  # CHW -> HWC (RGB)
    return img

def show_images(imgs, titles, cols=3):
    rows = (len(imgs) + cols - 1) // cols
    plt.figure(figsize=(5*cols, 5*rows))

    for i, img in enumerate(imgs):
        plt.subplot(rows, cols, i+1)

        # RGB image
        if img.ndim == 3 and img.shape[2] == 3:
            plt.imshow(img)  # already RGB

        # grayscale mask / edges
        elif img.ndim == 2:
            plt.imshow(img, cmap='gray')

        else:
            plt.imshow(img)

        plt.title(titles[i])
        plt.axis("off")

    plt.tight_layout()
    plt.show()

def bgr_to_rgb(img_bgr):
    return cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

"""7.3 Reflection Dataset (5-channel input)"""

class ReflectionDataset(Dataset):
    def __init__(self, pairs, img_size):
        self.pairs = pairs
        self.size  = (img_size, img_size)
        self.tf = T.Compose([
            T.ToPILImage(),
            T.Resize(self.size),
            T.ToTensor(),   # → [0,1]
        ])

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, idx):
        refl_bgr, clean_bgr = self.pairs[idx]

        # Safety check
        if refl_bgr is None or clean_bgr is None:
            raise ValueError(f"❌ ERROR: None image at index {idx}")

        # Convert for PyTorch
        refl_rgb  = cv2.cvtColor(refl_bgr, cv2.COLOR_BGR2RGB)
        clean_rgb = cv2.cvtColor(clean_bgr, cv2.COLOR_BGR2RGB)

        # Classical masks
        mask_u8  = classical_reflection_mask(refl_bgr)
        edges_u8 = classical_reflection_edges(refl_bgr)

        mask_t  = torch.from_numpy(cv2.resize(mask_u8, self.size) / 255.).float().unsqueeze(0)
        edges_t = torch.from_numpy(cv2.resize(edges_u8, self.size) / 255.).float().unsqueeze(0)

        refl_t  = self.tf(refl_rgb)
        clean_t = self.tf(clean_rgb)

        # Combine into 5-channel input
        inp_5ch = torch.cat([refl_t, mask_t, edges_t], dim=0)

        # Scale to [-1,1]
        return inp_5ch * 2 - 1, clean_t * 2 - 1


# Create loaders
img_size = CFG["gan_img_size"]

refl_train_ds = ReflectionDataset(sirr_train, img_size)
refl_test_ds  = ReflectionDataset(sirr_test,  img_size)

refl_train_dl = DataLoader(refl_train_ds, batch_size=CFG["batch_size"], shuffle=True)
refl_test_dl  = DataLoader(refl_test_ds,  batch_size=1, shuffle=False)

print("Train batches:", len(refl_train_dl), " Test:", len(refl_test_dl))

A_ref, B_ref = next(iter(refl_train_dl))
print("Input shape:", A_ref.shape, " Target shape:", B_ref.shape)

"""## Section 8 – Train on Reflections (SIRR)"""

G_refl = Pix2PixGenerator(in_ch=5, out_ch=3).to(device)
D_refl = PatchDiscriminator(in_ch=5+3).to(device)

optG_r = torch.optim.Adam(G_refl.parameters(), lr=CFG["lr_g"], betas=(0.5, 0.999))
optD_r = torch.optim.Adam(D_refl.parameters(), lr=CFG["lr_d"], betas=(0.5, 0.999))

print("Training on Reflections (SIRR)...")

for epoch in range(CFG["epochs_reflection"]):
    G_refl.train(); D_refl.train()
    D_losses = []; G_losses = []

    for A, B in refl_train_dl:   # A = reflected(5ch), B = clean(3ch)
        A = A.to(device); B = B.to(device)

        # --- Train D ---
        fakeB = G_refl(A).detach()
        real_pred = D_refl(A, B)
        fake_pred = D_refl(A, fakeB)

        lossD = 0.5 * (
            F.mse_loss(real_pred, torch.ones_like(real_pred)) +
            F.mse_loss(fake_pred, torch.zeros_like(fake_pred))
        )

        optD_r.zero_grad()
        lossD.backward()
        optD_r.step()

        # --- Train G ---
        fakeB = G_refl(A)
        fake_pred = D_refl(A, fakeB)

        adv  = F.mse_loss(fake_pred, torch.ones_like(fake_pred))
        l1   = F.l1_loss(fakeB, B)
        grad = gradient_loss(fakeB, B)

        lossG = adv + 50*l1 + 5*grad

        optG_r.zero_grad()
        lossG.backward()
        optG_r.step()

        D_losses.append(lossD.item())
        G_losses.append(lossG.item())

    print(f"[Refl] Epoch {epoch+1}/{CFG['epochs_reflection']} "
          f"D={np.mean(D_losses):.4f} G={np.mean(G_losses):.4f}")

    # --- Visualization ---
    G_refl.eval()
    with torch.no_grad():
        A_s, B_s = next(iter(refl_test_dl))
        A_s, B_s = A_s.to(device), B_s.to(device)

        out = G_refl(A_s)[0]

        imgs = [
            tensor_to_image(A_s[0][:3]),  # only RGB, no mask/edges
            tensor_to_image(out),
            tensor_to_image(B_s[0]),
        ]
        show_images(imgs, ["Reflected Input", "GAN Output", "GT Clean"], cols=3)


torch.save(G_refl.state_dict(), "G_refl_5ch.pt")
torch.save(D_refl.state_dict(), "D_refl_5ch.pt")
print("Saved reflection models.")